export const SET_INPUT_VALUE = 'core/SET_INPUT_VALUE';
export const SET_SEARCH_ORGANIZATION = 'core/SET_SEARCH_ORGANIZATION';
export const SET_ORGANIZATION_LOADING = 'core/SET_ORGANIZATION_LOADING';
export const SET_ORGANIZATION_DATA = 'core/SET_ORGANIZATION_DATA';
